### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by ajeetraina** [BhanuKorthiwada/RedisZindagi#1]
@BhanuKorthiwada  Went through the README and looks like it needs a lot of work to explain how to configure the app.
Missing instructions:
1. How to configure SMTP.
2.  Complete instruction related to SMS message.

Can you please add.

**Comment by BhanuKorthiwada** [comment]
sure @ajeetraina, will do.

**Comment by BhanuKorthiwada** [comment]
README updated
